# site settings
title: Aymane Mimoun Data Scientist | ML Engineer
subtitle: ""
email: aym.mimoun@gmail.com
description: >
  Portfolio personnel – Machine Learning, Deep Learning, MLOps.  
  Projets robustes, reproductibles, orientés bonnes pratiques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aymane-ML.github.io" # the base hostname & protocol for your site
author: Aymane Mimoun

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Aymane-ML
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
